DECLARE
@AdminRoleID UNIQUEIDENTIFIER = 'DDB8F0FD-B8A2-4582-B513-99605CA8B7F0',
@UserEmail VARCHAR(50) = '',
@UserID UNIQUEIDENTIFIER

SET @UserID = (SELECT ID FROM AspNetUsers WHERE Email = @UserEmail)

IF NOT EXISTS (SELECT TOP 1 1 FROM AspNetUserRoles WHERE UserID = @UserID AND RoleID = @AdminRoleID)
BEGIN
	INSERT INTO AspNetUserRoles(UserID, RoleID)
	SELECT UserID = @UserID, RoleID = @AdminRoleID
END